version: "3.7"

services:
  rust-sandbox:
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: dev
    command: "sleep infinity"
    tty: true
    volumes: 
      - type: bind
        source: ../
        target: /src
